//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.SSO.Storage
{
    public class ClientModel
    {
        public Int32 Id { get; set; }
        public Int32 AbsoluteRefreshTokenLifetime { get; set; }
        public Int32 AccessTokenLifetime { get; set; }
        public Int32 AccessTokenType { get; set; }
        public Boolean AllowAccessTokensViaBrowser { get; set; }
        public Boolean AllowOfflineAccess { get; set; }
        public Boolean AllowPlainTextPkce { get; set; }
        public Boolean AllowRememberConsent { get; set; }
        public String AllowedIdentityTokenSigningAlgorithms { get; set; }
        public Boolean AlwaysIncludeUserClaimsInIdToken { get; set; }
        public Boolean AlwaysSendClientClaims { get; set; }
        public Int32 AuthorizationCodeLifetime { get; set; }
        public Boolean BackChannelLogoutSessionRequired { get; set; }
        public String BackChannelLogoutUri { get; set; }
        public String ClientClaimsPrefix { get; set; }
        public String ClientId { get; set; }
        public String ClientName { get; set; }
        public String ClientUri { get; set; }
        public Int32? ConsentLifetime { get; set; }
        public DateTime Created { get; set; }
        public String Description { get; set; }
        public Int32 DeviceCodeLifetime { get; set; }
        public Boolean EnableLocalLogin { get; set; }
        public Boolean Enabled { get; set; }
        public Boolean FrontChannelLogoutSessionRequired { get; set; }
        public String FrontChannelLogoutUri { get; set; }
        public Int32 IdentityTokenLifetime { get; set; }
        public Boolean IncludeJwtId { get; set; }
        public DateTime? LastAccessed { get; set; }
        public String LogoUri { get; set; }
        public Boolean NonEditable { get; set; }
        public String PairWiseSubjectSalt { get; set; }
        public String ProtocolType { get; set; }
        public Int32 RefreshTokenExpiration { get; set; }
        public Int32 RefreshTokenUsage { get; set; }
        public Boolean RequireClientSecret { get; set; }
        public Boolean RequireConsent { get; set; }
        public Boolean RequirePkce { get; set; }
        public Boolean RequireRequestObject { get; set; }
        public Int32 SlidingRefreshTokenLifetime { get; set; }
        public Boolean UpdateAccessTokenClaimsOnRefresh { get; set; }
        public DateTime? Updated { get; set; }
        public String UserCodeType { get; set; }
        public Int32? UserSsoLifetime { get; set; }
    }
    public class ClientCorsOriginModel
    {
        public Int32 Id { get; set; }
        public Int32 ClientId { get; set; }
        public String Origin { get; set; }
    }
    public class IdentityResourceModel
    {
        public Int32 Id { get; set; }
        public DateTime Created { get; set; }
        public String Description { get; set; }
        public String DisplayName { get; set; }
        public Boolean Emphasize { get; set; }
        public Boolean Enabled { get; set; }
        public String Name { get; set; }
        public Boolean NonEditable { get; set; }
        public Boolean Required { get; set; }
        public Boolean ShowInDiscoveryDocument { get; set; }
        public DateTime? Updated { get; set; }
    }
    public class ApiResourceModel
    {
        public Int32 Id { get; set; }
        public String AllowedAccessTokenSigningAlgorithms { get; set; }
        public DateTime Created { get; set; }
        public String Description { get; set; }
        public String DisplayName { get; set; }
        public Boolean Enabled { get; set; }
        public DateTime? LastAccessed { get; set; }
        public String Name { get; set; }
        public Boolean NonEditable { get; set; }
        public Boolean ShowInDiscoveryDocument { get; set; }
        public DateTime? Updated { get; set; }
    }
    public class ApiScopeModel
    {
        public Int32 Id { get; set; }
        public String Description { get; set; }
        public String DisplayName { get; set; }
        public Boolean Emphasize { get; set; }
        public Boolean Enabled { get; set; }
        public String Name { get; set; }
        public Boolean Required { get; set; }
        public Boolean ShowInDiscoveryDocument { get; set; }
    }
    public class PersistedGrantModel
    {
        public String Key { get; set; }
        public String ClientId { get; set; }
        public DateTime? ConsumedTime { get; set; }
        public DateTime CreationTime { get; set; }
        public String Data { get; set; }
        public String Description { get; set; }
        public DateTime? Expiration { get; set; }
        public String SessionId { get; set; }
        public String SubjectId { get; set; }
        public String Type { get; set; }
    }
    public class DeviceFlowCodesModel
    {
        public String UserCode { get; set; }
        public String ClientId { get; set; }
        public DateTime CreationTime { get; set; }
        public String Data { get; set; }
        public String Description { get; set; }
        public String DeviceCode { get; set; }
        public DateTime Expiration { get; set; }
        public String SessionId { get; set; }
        public String SubjectId { get; set; }
    }
}
