//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.SSO.Storage
{
    public class GetClientByIdAsyncRequestModel
    {
        public String clientId { get; set; }
    }
    public class GetClientByIdAsyncResponseModel
    {
        public Int32 ClientId { get; set; }
        public Int32 ClientAbsoluteRefreshTokenLifetime { get; set; }
        public Int32 ClientAccessTokenLifetime { get; set; }
        public Int32 ClientAccessTokenType { get; set; }
        public Boolean ClientAllowAccessTokensViaBrowser { get; set; }
        public Boolean ClientAllowOfflineAccess { get; set; }
        public Boolean ClientAllowPlainTextPkce { get; set; }
        public Boolean ClientAllowRememberConsent { get; set; }
        public String ClientAllowedIdentityTokenSigningAlgorithms { get; set; }
        public Boolean ClientAlwaysIncludeUserClaimsInIdToken { get; set; }
        public Boolean ClientAlwaysSendClientClaims { get; set; }
        public Int32 ClientAuthorizationCodeLifetime { get; set; }
        public Boolean ClientBackChannelLogoutSessionRequired { get; set; }
        public String ClientBackChannelLogoutUri { get; set; }
        public String ClientClientClaimsPrefix { get; set; }
        public String ClientClientId { get; set; }
        public String ClientClientName { get; set; }
        public String ClientClientUri { get; set; }
        public Int32? ClientConsentLifetime { get; set; }
        public DateTime ClientCreated { get; set; }
        public String ClientDescription { get; set; }
        public Int32 ClientDeviceCodeLifetime { get; set; }
        public Boolean ClientEnableLocalLogin { get; set; }
        public Boolean ClientEnabled { get; set; }
        public Boolean ClientFrontChannelLogoutSessionRequired { get; set; }
        public String ClientFrontChannelLogoutUri { get; set; }
        public Int32 ClientIdentityTokenLifetime { get; set; }
        public Boolean ClientIncludeJwtId { get; set; }
        public DateTime? ClientLastAccessed { get; set; }
        public String ClientLogoUri { get; set; }
        public Boolean ClientNonEditable { get; set; }
        public String ClientPairWiseSubjectSalt { get; set; }
        public String ClientProtocolType { get; set; }
        public Int32 ClientRefreshTokenExpiration { get; set; }
        public Int32 ClientRefreshTokenUsage { get; set; }
        public Boolean ClientRequireClientSecret { get; set; }
        public Boolean ClientRequireConsent { get; set; }
        public Boolean ClientRequirePkce { get; set; }
        public Boolean ClientRequireRequestObject { get; set; }
        public Int32 ClientSlidingRefreshTokenLifetime { get; set; }
        public Boolean ClientUpdateAccessTokenClaimsOnRefresh { get; set; }
        public DateTime? ClientUpdated { get; set; }
        public String ClientUserCodeType { get; set; }
        public Int32? ClientUserSsoLifetime { get; set; }
        public Int32? ClientCorsOriginId { get; set; }
        public Int32? ClientCorsOriginClientId { get; set; }
        public String ClientCorsOriginOrigin { get; set; }
        public Int32? ClientGrantTypeId { get; set; }
        public Int32? ClientGrantTypeClientId { get; set; }
        public String ClientGrantTypeGrantType { get; set; }
        public Int32? ClientScopeId { get; set; }
        public Int32? ClientScopeClientId { get; set; }
        public String ClientScopeScope { get; set; }
        public Int32? ClientClaimId { get; set; }
        public Int32? ClientClaimClientId { get; set; }
        public String ClientClaimType { get; set; }
        public String ClientClaimValue { get; set; }
        public Int32? ClientSecretId { get; set; }
        public Int32? ClientSecretClientId { get; set; }
        public DateTime? ClientSecretCreated { get; set; }
        public String ClientSecretDescription { get; set; }
        public DateTime? ClientSecretExpiration { get; set; }
        public String ClientSecretType { get; set; }
        public String ClientSecretValue { get; set; }
        public Int32? ClientIdPRestrictionId { get; set; }
        public Int32? ClientIdPRestrictionClientId { get; set; }
        public String ClientIdPRestrictionProvider { get; set; }
        public Int32? ClientPostLogoutRedirectUriId { get; set; }
        public Int32? ClientPostLogoutRedirectUriClientId { get; set; }
        public String ClientPostLogoutRedirectUriPostLogoutRedirectUri { get; set; }
        public Int32? ClientPropertyId { get; set; }
        public Int32? ClientPropertyClientId { get; set; }
        public String ClientPropertyKey { get; set; }
        public String ClientPropertyValue { get; set; }
        public Int32? ClientRedirectUriId { get; set; }
        public Int32? ClientRedirectUriClientId { get; set; }
        public String ClientRedirectUriRedirectUri { get; set; }
    }
}
