//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.SSO.Storage
{
    public class GetAllIdentityResourcesAsyncRequestModel
    {
    }
    public class GetAllIdentityResourcesAsyncResponseModel
    {
        public Int32 IdentityResourceId { get; set; }
        public DateTime IdentityResourceCreated { get; set; }
        public String IdentityResourceDescription { get; set; }
        public String IdentityResourceDisplayName { get; set; }
        public Boolean IdentityResourceEmphasize { get; set; }
        public Boolean IdentityResourceEnabled { get; set; }
        public String IdentityResourceName { get; set; }
        public Boolean IdentityResourceNonEditable { get; set; }
        public Boolean IdentityResourceRequired { get; set; }
        public Boolean IdentityResourceShowInDiscoveryDocument { get; set; }
        public DateTime? IdentityResourceUpdated { get; set; }
        public Int32? IdentityResourceClaimId { get; set; }
        public Int32? IdentityResourceClaimIdentityResourceId { get; set; }
        public String IdentityResourceClaimType { get; set; }
        public Int32? IdentityResourcePropertyId { get; set; }
        public Int32? IdentityResourcePropertyIdentityResourceId { get; set; }
        public String IdentityResourcePropertyKey { get; set; }
        public String IdentityResourcePropertyValue { get; set; }
    }
    public class GetAllApiResourcesAsyncRequestModel
    {
    }
    public class GetAllApiResourcesAsyncResponseModel
    {
        public Int32 ApiResourceId { get; set; }
        public String ApiResourceAllowedAccessTokenSigningAlgorithms { get; set; }
        public DateTime ApiResourceCreated { get; set; }
        public String ApiResourceDescription { get; set; }
        public String ApiResourceDisplayName { get; set; }
        public Boolean ApiResourceEnabled { get; set; }
        public DateTime? ApiResourceLastAccessed { get; set; }
        public String ApiResourceName { get; set; }
        public Boolean ApiResourceNonEditable { get; set; }
        public Boolean ApiResourceShowInDiscoveryDocument { get; set; }
        public DateTime? ApiResourceUpdated { get; set; }
        public Int32? ApiResourceSecretId { get; set; }
        public Int32? ApiResourceSecretApiResourceId { get; set; }
        public DateTime? ApiResourceSecretCreated { get; set; }
        public String ApiResourceSecretDescription { get; set; }
        public DateTime? ApiResourceSecretExpiration { get; set; }
        public String ApiResourceSecretType { get; set; }
        public String ApiResourceSecretValue { get; set; }
        public Int32? ApiResourceScopeId { get; set; }
        public Int32? ApiResourceScopeApiResourceId { get; set; }
        public String ApiResourceScopeScope { get; set; }
        public Int32? ApiResourceClaimId { get; set; }
        public Int32? ApiResourceClaimApiResourceId { get; set; }
        public String ApiResourceClaimType { get; set; }
        public Int32? ApiResourcePropertyId { get; set; }
        public Int32? ApiResourcePropertyApiResourceId { get; set; }
        public String ApiResourcePropertyKey { get; set; }
        public String ApiResourcePropertyValue { get; set; }
    }
    public class GetAllApiScopesAsyncRequestModel
    {
    }
    public class GetAllApiScopesAsyncResponseModel
    {
        public Int32 ApiScopeId { get; set; }
        public String ApiScopeDescription { get; set; }
        public String ApiScopeDisplayName { get; set; }
        public Boolean ApiScopeEmphasize { get; set; }
        public Boolean ApiScopeEnabled { get; set; }
        public String ApiScopeName { get; set; }
        public Boolean ApiScopeRequired { get; set; }
        public Boolean ApiScopeShowInDiscoveryDocument { get; set; }
        public Int32? ApiScopeClaimId { get; set; }
        public Int32? ApiScopeClaimScopeId { get; set; }
        public String ApiScopeClaimType { get; set; }
        public Int32? ApiScopePropertyId { get; set; }
        public String ApiScopePropertyKey { get; set; }
        public Int32? ApiScopePropertyScopeId { get; set; }
        public String ApiScopePropertyValue { get; set; }
    }
    public class GetApiResourcesByNameAsyncRequestModel
    {
        public List<String> apiResourceNames { get; set; }
    }
    public class GetApiResourcesByNameAsyncResponseModel
    {
        public Int32 ApiResourceId { get; set; }
        public String ApiResourceAllowedAccessTokenSigningAlgorithms { get; set; }
        public DateTime ApiResourceCreated { get; set; }
        public String ApiResourceDescription { get; set; }
        public String ApiResourceDisplayName { get; set; }
        public Boolean ApiResourceEnabled { get; set; }
        public DateTime? ApiResourceLastAccessed { get; set; }
        public String ApiResourceName { get; set; }
        public Boolean ApiResourceNonEditable { get; set; }
        public Boolean ApiResourceShowInDiscoveryDocument { get; set; }
        public DateTime? ApiResourceUpdated { get; set; }
        public Int32? ApiResourceSecretId { get; set; }
        public Int32? ApiResourceSecretApiResourceId { get; set; }
        public DateTime? ApiResourceSecretCreated { get; set; }
        public String ApiResourceSecretDescription { get; set; }
        public DateTime? ApiResourceSecretExpiration { get; set; }
        public String ApiResourceSecretType { get; set; }
        public String ApiResourceSecretValue { get; set; }
        public Int32? ApiResourceScopeId { get; set; }
        public Int32? ApiResourceScopeApiResourceId { get; set; }
        public String ApiResourceScopeScope { get; set; }
        public Int32? ApiResourceClaimId { get; set; }
        public Int32? ApiResourceClaimApiResourceId { get; set; }
        public String ApiResourceClaimType { get; set; }
        public Int32? ApiResourcePropertyId { get; set; }
        public Int32? ApiResourcePropertyApiResourceId { get; set; }
        public String ApiResourcePropertyKey { get; set; }
        public String ApiResourcePropertyValue { get; set; }
    }
    public class GetApiResourcesByScopeNameAsyncRequestModel
    {
        public List<String> scopeNames { get; set; }
    }
    public class GetApiResourcesByScopeNameAsyncResponseModel
    {
        public Int32 ApiResourceId { get; set; }
        public String ApiResourceAllowedAccessTokenSigningAlgorithms { get; set; }
        public DateTime ApiResourceCreated { get; set; }
        public String ApiResourceDescription { get; set; }
        public String ApiResourceDisplayName { get; set; }
        public Boolean ApiResourceEnabled { get; set; }
        public DateTime? ApiResourceLastAccessed { get; set; }
        public String ApiResourceName { get; set; }
        public Boolean ApiResourceNonEditable { get; set; }
        public Boolean ApiResourceShowInDiscoveryDocument { get; set; }
        public DateTime? ApiResourceUpdated { get; set; }
        public Int32? ApiResourceSecretId { get; set; }
        public Int32? ApiResourceSecretApiResourceId { get; set; }
        public DateTime? ApiResourceSecretCreated { get; set; }
        public String ApiResourceSecretDescription { get; set; }
        public DateTime? ApiResourceSecretExpiration { get; set; }
        public String ApiResourceSecretType { get; set; }
        public String ApiResourceSecretValue { get; set; }
        public Int32? ApiResourceScopeId { get; set; }
        public Int32? ApiResourceScopeApiResourceId { get; set; }
        public String ApiResourceScopeScope { get; set; }
        public Int32? ApiResourceClaimId { get; set; }
        public Int32? ApiResourceClaimApiResourceId { get; set; }
        public String ApiResourceClaimType { get; set; }
        public Int32? ApiResourcePropertyId { get; set; }
        public Int32? ApiResourcePropertyApiResourceId { get; set; }
        public String ApiResourcePropertyKey { get; set; }
        public String ApiResourcePropertyValue { get; set; }
    }
    public class GetApiScopesByNameAsyncRequestModel
    {
        public List<String> scopeNames { get; set; }
    }
    public class GetApiScopesByNameAsyncResponseModel
    {
        public Int32 ApiScopeId { get; set; }
        public String ApiScopeDescription { get; set; }
        public String ApiScopeDisplayName { get; set; }
        public Boolean ApiScopeEmphasize { get; set; }
        public Boolean ApiScopeEnabled { get; set; }
        public String ApiScopeName { get; set; }
        public Boolean ApiScopeRequired { get; set; }
        public Boolean ApiScopeShowInDiscoveryDocument { get; set; }
        public Int32? ApiScopeClaimId { get; set; }
        public Int32? ApiScopeClaimScopeId { get; set; }
        public String ApiScopeClaimType { get; set; }
        public Int32? ApiScopePropertyId { get; set; }
        public String ApiScopePropertyKey { get; set; }
        public Int32? ApiScopePropertyScopeId { get; set; }
        public String ApiScopePropertyValue { get; set; }
    }
}
